api_default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: "<%= ENV.fetch('DATABASE_NAME') %>"
  host: "<%= ENV.fetch('DATABASE_HOST') %>"
  port: "<%= ENV.fetch('DATABASE_PORT', 5432) %>"
  username: "<%= ENV.fetch('DATABASE_USERNAME') %>"
  password: "<%= ENV.fetch('DATABASE_PASSWORD') %>"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default