version: '3'
services:
  rails:
    build: .
    command: 'bash -c "rm -f /var/run/rails.pid && bundle exec rails s -b 0.0.0.0 -p 3001 --pid /var/run/rails.pid"'
    ports:
      - "3001:3001"
    environment:
      BUNDLE_PATH: /bundle/2.7/
      RAILS_ENV: $RAILS_ENV
    volumes:
      - .:/app
      - ./bundle:/bundle
    depends_on:
      - pg

  pg:
    image: postgres:12
    environment: 
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    driver: local
