version: '3'
services:
  rails:
    build: .
    command: bundle exec rails s -b 0.0.0.0 -p 3001
    ports:
      - "3001:3001"
    environment:
      BUNDLE_PATH: /bundle/2.7/
      RAILS_ENV: $RAILS_ENV
      USER: $USER
      HOME: /app
      EDITOR: vim
    volumes:
      - .:/app
      - ./bundle:/bundle
      - ../gems:/localgems
    user: "1000:1000"
    depends_on:
      - pg

  pg:
    image: postgres:12
    environment: 
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    driver: local
