source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

# == core
gem 'rails', '~> 6.0.3', '>= 6.0.3.1'

# == users
gem 'devise', '~> 4.7.1'
gem 'omniauth', '~> 1.9.1'
gem 'omniauth-google-oauth2', '~> 0.8.0'

# == databases
gem 'pg', '~> 1.2.3'

# == webserver & middleware
gem 'puma', '~> 4.1'
gem 'rack-cors', '~> 1.1.1'

# == utils
gem 'bootsnap', '>= 1.4.2', require: false

group :development, :test do
  gem 'dotenv-rails', '~> 2.7.5'
  gem 'pry'
end

group :development do
  gem 'listen', '~> 3.2'
  # TODO: set up spring for docker
  # gem 'spring'
  # gem 'spring-watcher-listen', '~> 2.0.0'
end
